# This file was generated by GoReleaser. DO NOT EDIT.
cask "classreach" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "8c13c7633225a56c1d8664110fd357c7727c545b6c7351f498b0807961968238"
      url "https://github.com/jwmoss/classreach/releases/download/v#{version}/classreach_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "4438df91e7eba10af36171df48458e002f6aae754e51fabd5cbc5f1ba37dc215"
      url "https://github.com/jwmoss/classreach/releases/download/v#{version}/classreach_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "e038f4e8afa021ae455899ac95b475b0fcf8f3607a685edc699cb3609cb7cc76"
      url "https://github.com/jwmoss/classreach/releases/download/v#{version}/classreach_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "7b891bb289aa938c7ab80b49314e173000f60e86805858a4470ab1a99d3cdb7e"
      url "https://github.com/jwmoss/classreach/releases/download/v#{version}/classreach_#{version}_linux_arm64.tar.gz"
    end
  end

  name "classreach"
  desc "Command-line client for the ClassReach private API"
  homepage "https://github.com/jwmoss/classreach"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "classreach"

  # No zap stanza required

end
