# This file was generated by GoReleaser. DO NOT EDIT.
cask "classreach" do
  version "0.1.2"

  on_macos do
    on_intel do
      sha256 "6932ac6d90f25f1ec170e78c7f05d5dea1bd0311f5ca61d54f8b28d23ddaaa31"
      url "https://github.com/jwmoss/classreach/releases/download/v#{version}/classreach_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "37752daa6bda6bfabfa8328b2e403e1be15cb62aebd64117d7805745f1815c81"
      url "https://github.com/jwmoss/classreach/releases/download/v#{version}/classreach_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "bb93cbea22578111ecb293aa0c6b2c86d1d00bb31831966809336fd9bff5e50f"
      url "https://github.com/jwmoss/classreach/releases/download/v#{version}/classreach_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "5c7109884457f04f86d100e686d3a74017e0ee560a0dc72dccda802c185060d1"
      url "https://github.com/jwmoss/classreach/releases/download/v#{version}/classreach_#{version}_linux_arm64.tar.gz"
    end
  end

  name "classreach"
  desc "Command-line client for the ClassReach private API"
  homepage "https://github.com/jwmoss/classreach"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "classreach"

  # No zap stanza required

end
