# This file was generated by GoReleaser. DO NOT EDIT.
cask "classreach" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "3cf71a051614d82aed3307b94292b2e6ddaf1712db76032e1ed044f2739a9be7"
      url "https://github.com/jwmoss/classreach/releases/download/v#{version}/classreach_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "e6ed45afd426f099a349e6c11aa2ca8fbafe6157a012c1bd0994ab2771f7cf92"
      url "https://github.com/jwmoss/classreach/releases/download/v#{version}/classreach_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "42a708f19ae5f4a430ec0ca3a6ad88ab867664c4efe1c917b46601fe9f77161d"
      url "https://github.com/jwmoss/classreach/releases/download/v#{version}/classreach_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "745a7969ef7949e94a0a1061dc45263ae82101c54a98496c491695789e68e853"
      url "https://github.com/jwmoss/classreach/releases/download/v#{version}/classreach_#{version}_linux_arm64.tar.gz"
    end
  end

  name "classreach"
  desc "Command-line client for the ClassReach private API"
  homepage "https://github.com/jwmoss/classreach"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "classreach"

  # No zap stanza required

end
