# This file was generated by GoReleaser. DO NOT EDIT.
cask "skycli" do
  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "611ff63e7702511419326f72508e69a81e439b02211b7d4befe196690f4366e2"
      url "https://github.com/jwmoss/skycli/releases/download/v#{version}/skycli_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "e0fe466b1800c76eb5f749dbb02405b4954c0501b28f45f53d3afed84a96f274"
      url "https://github.com/jwmoss/skycli/releases/download/v#{version}/skycli_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "fc615600248f2c30e72c1a09046ed26d4d139db4f82c5f7da702d35145adce4d"
      url "https://github.com/jwmoss/skycli/releases/download/v#{version}/skycli_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "a3107d4a06ec30538e610f1e5a7a3b683a95e32cf59c826249e6a99923274275"
      url "https://github.com/jwmoss/skycli/releases/download/v#{version}/skycli_#{version}_linux_amd64.tar.gz"
    end
  end

  name "skycli"
  desc "Unofficial CLI for the Skylight Calendar private API"
  homepage "https://github.com/jwmoss/skycli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "skycli"

  # No zap stanza required
end
