# This file was generated by GoReleaser. DO NOT EDIT.
cask "skycli" do
  version "0.2.1"

  on_macos do
    on_arm do
      sha256 "92dce057fa4f12f0987f1acc3c8c123a1cc27285ccc8b69c45536c2839fc6f49"
      url "https://github.com/jwmoss/skycli/releases/download/v#{version}/skycli_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "0ad7c69da78c0bb2aee1c9cf22d5e29fb5c9f45e7453a905df6b8b62c0c833fe"
      url "https://github.com/jwmoss/skycli/releases/download/v#{version}/skycli_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "747131d013bd1b7ed19de3f8731d2fbaa251d2b524548f4332a524cb79ebdf25"
      url "https://github.com/jwmoss/skycli/releases/download/v#{version}/skycli_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "30dd551812bbc5c760a81f6ff37624a479a40f8c76ca9cf49dc246425fddd7c0"
      url "https://github.com/jwmoss/skycli/releases/download/v#{version}/skycli_#{version}_linux_amd64.tar.gz"
    end
  end

  name "skycli"
  desc "Unofficial CLI for the Skylight Calendar private API"
  homepage "https://github.com/jwmoss/skycli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "skycli"

  # No zap stanza required
end
