# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Goveetl < Formula
  desc "Command-line client for Govee cloud, app, and LAN APIs"
  homepage "https://github.com/jwmoss/goveetl"
  version "1.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jwmoss/goveetl/releases/download/v1.2.1/goveetl_1.2.1_darwin_amd64.tar.gz"
      sha256 "03e69b6e040e25c46dd4c10cb4e6fcb35fe09628236709e3e6b0b050becff591"

      define_method(:install) do
        bin.install "goveetl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jwmoss/goveetl/releases/download/v1.2.1/goveetl_1.2.1_darwin_arm64.tar.gz"
      sha256 "ffec6c8950ba50bef8a8217a34587ae4606e9d02b15f8ef8b12f33449025beba"

      define_method(:install) do
        bin.install "goveetl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jwmoss/goveetl/releases/download/v1.2.1/goveetl_1.2.1_linux_amd64.tar.gz"
      sha256 "186ea353d7d59789cb777964a13760537aa92ee17b8af7ae38fefda1574db76b"
      define_method(:install) do
        bin.install "goveetl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jwmoss/goveetl/releases/download/v1.2.1/goveetl_1.2.1_linux_arm64.tar.gz"
      sha256 "9bf279841607b1fa41327d4113fe25fdf7099ecdfd795793d825da72b1b7ed83"
      define_method(:install) do
        bin.install "goveetl"
      end
    end
  end

  test do
    system "#{bin}/goveetl", "version"
  end
end
