# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Skycli < Formula
  desc "Unofficial CLI for the Skylight Calendar private API"
  homepage "https://github.com/jwmoss/skycli"
  version "0.1.9"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jwmoss/skycli/releases/download/v0.1.9/skycli_0.1.9_darwin_amd64.tar.gz"
      sha256 "2c4b76b8b18ff5e9e8b141727f0cd5da2e107ba33493d95a4865179d9b4b8811"

      define_method(:install) do
        bin.install "skycli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jwmoss/skycli/releases/download/v0.1.9/skycli_0.1.9_darwin_arm64.tar.gz"
      sha256 "71938fd2a4aa2b9dafc482429aeea41702378e5bb2b3d884eae53349d5a2f801"

      define_method(:install) do
        bin.install "skycli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jwmoss/skycli/releases/download/v0.1.9/skycli_0.1.9_linux_amd64.tar.gz"
      sha256 "1aa6d9d4dbca78d9af8e8df72363948d67ec764a10e174e12b17a0c39f589e4e"
      define_method(:install) do
        bin.install "skycli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jwmoss/skycli/releases/download/v0.1.9/skycli_0.1.9_linux_arm64.tar.gz"
      sha256 "dffe8e77c2ae3caf78ec7c0ac08e61b3820facc5c4219cb20bf9abef9dd47f97"
      define_method(:install) do
        bin.install "skycli"
      end
    end
  end

  test do
    system "#{bin}/skycli", "version"
  end
end
