# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Skycli < Formula
  desc "Unofficial CLI for the Skylight Calendar private API"
  homepage "https://github.com/jwmoss/skycli"
  version "0.1.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jwmoss/skycli/releases/download/v0.1.4/skycli_0.1.4_darwin_amd64.tar.gz"
      sha256 "47becb738db8d7e797324240a3fedbe6d889bc933a5eae380aa1bcce3194f723"

      define_method(:install) do
        bin.install "skycli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jwmoss/skycli/releases/download/v0.1.4/skycli_0.1.4_darwin_arm64.tar.gz"
      sha256 "220ff3ac61fd3d12e575abb334ec1dfbe8ed5377c5d9e02aae0d6206922aeeae"

      define_method(:install) do
        bin.install "skycli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jwmoss/skycli/releases/download/v0.1.4/skycli_0.1.4_linux_amd64.tar.gz"
      sha256 "faecd216d7161696a2f20084ffa54192826d2f2698b64a6c067a50b337511cef"
      define_method(:install) do
        bin.install "skycli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jwmoss/skycli/releases/download/v0.1.4/skycli_0.1.4_linux_arm64.tar.gz"
      sha256 "840ccb5d2a56a36bcec6bf2c52f5ffcfca48a5e19eea4efa26dc3f2b93296226"
      define_method(:install) do
        bin.install "skycli"
      end
    end
  end

  test do
    system "#{bin}/skycli", "version"
  end
end
